### ISSUE TITLE
Migration instructions coming from TF cloud

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#297]
TF cloud doesn't make it easy to migrate states to other backends.

There is https://developer.hashicorp.com/terraform/tutorials/cloud/cloud-state-api#download-the-state-file, yet many people would probably appreciate a more "simple" approach to do this.

As I've just gone through this, I've created a gist to simplify the process: https://gist.github.com/pat-s/6cc1a931866e869f1adb1c84f715ef92. Feel free to adapt/reuse, just wanted to drop it here for future people to get up to speed quickly!

**Comment by leg100** [comment]
Thank you, I'll have a look into using this.

It should be no different to migrating from one TFC organization to another, or indeed from TFC to TFE and vice-versa. But is that just as difficult?

Or are you also migrating from using the [cloud block](https://developer.hashicorp.com/terraform/cli/cloud/settings) to the [remote backend](https://developer.hashicorp.com/terraform/language/settings/backends/remote)? I don't know if that makes migrating state any more difficult, but if it does, OTF does support both, so you can keep whichever one you are currently using.

**Comment by pat-s** [comment]
> Or are you also migrating from using the [cloud block](https://developer.hashicorp.com/terraform/cli/cloud/settings) to the [remote backend](https://developer.hashicorp.com/terraform/language/settings/backends/remote)?

Yes, I did that.
Oh dear, probably took the hard route without need then ;)
I assumed OTF requires the "remote" backend as you list it in https://docs.otf.ninja/en/latest/#installation. 

I think a short paragraph on how to migrate and adapt the backend block to `cloud` one which refers to the OTF URL would be helpful and avoid issues for users migrating (or like me assuming the `remote` backend is required 😅 )

**Comment by pat-s** [comment]
Still having trouble here.
While for the first workspace I went "TFC" -> "remote" -> "TFC" (which worked well) I am now attempting to go "TFC" -> "TFC". 

The only different is that I am now specifying `hostname` in the backend config. 

```tf
terraform {
  cloud {
    organization = "<org>"
    hostname     = "<hostname>"
    workspaces {
      name = "<workspace>"
    }
  }
}
```

Then I login via `terraform login` and I can see that the runs are streamed in OTF. **The issue though** is that the state is not pushed, hence all resources are attempted to be recreated.

`terraform state push` only works with remote backends. Hence I am wondering if "TFC" -> "TFC" is possible at all or one has to go the long way of first migrating to a "remote" backend and then back to TFC?

How did you do the transfer initially? I must be overlooking something... 🤔

**Comment by pat-s** [comment]
I am also failing uploading a state version via the API following the approach outlined in the OP.
It worked for the OTF instance running on k8s and fails now on the VM hosted instance.

All variables are properly expanded. Could this be an issue in OTF?
The state file in the payload looks good. Maybe a proxy issue?

(I am currently stuck here. Unless I am overlooking something, there does not seem to be an "easy" way to migrate from TFC to TFE/OTF and using the API approach somehow errors atm fro me). Any help/hint is highly appreciated!

```bash
curl -v \
  --header "Authorization: Bearer "${TOKEN_REMOTE_BACKEND}"" \
  --header "Content-Type: application/vnd.api+json" \
  --request POST \
  --data @payload.json \
  https://"${REMOTE_BACKEND_URL}"/api/v2/workspaces/"${OTF_WORKSPACE_ID}"/state-versions

{"errors":[{"title":"Not Found","detail":"json: cannot unmarshal array into Go struct field StateOutput.Outputs.Value of type string","status":"404"}]}
*
```

**Comment by leg100** [comment]
Looks like your state upload error is a legitimate bug. OTF assumes state output values are strings, whereas they can of course being many things, including an array, which is what you have. I'll raise an issue. For now, you'll have to workaround it by ensuring all state outputs are strings. Sorry about that.

As for migration, I'm hitting the same problems as you. It seems the "remote" backend is more flexible and let's you migrate state in and out of TFC. While the "cloud" backend (let's call it that rather than "TFC" for clarity) is more restrictive. Even migrating from the "cloud" backend to a "local" backend I get the following error:

> $ terraform init
>
> Initializing the backend...
> Migrating from Terraform Cloud to local state.
> ╷
> │ Error: Migrating state from Terraform Cloud to another backend is not yet implemented.
> │
> │ Please use the API to do this: https://www.terraform.io/docs/cloud/api/state-versions.html
> │
> │
> ╵

And if I add the `-migrate-state` flag, I get:

> $ terraform init -migrate-state
> 
> Initializing Terraform Cloud...
> ╷
> │ Error: Invalid command-line option
> │
> │ The -migrate-state option is for migration between state backends only, and is not applicable when using
> │ Terraform Cloud.
> │
> │ State storage is handled automatically by Terraform Cloud and so the state storage location is not configurable.
╵

And as you say, migrating from one "cloud" backend to another "cloud" backend, i.e. changing the hostname from `app.terraform.io` to your OTF hostname succeeds without error, but it neglects to migrate the state. I suppose TFC is only hosted on one hostname, `app.terraform.io`, and one would never need to perform this particular migration.

But that begs the question, how do people migrate state - when using the "cloud" backend - from Terraform Cloud to Terraform Enterprise, or vice-versa? I suspect your API-driven approach is unfortunately how they do it.

I will document a migration path once you've successfully demonstrated this approach (state bugs in OTF notwithstanding...).

**Comment by leg100** [comment]
...and it does indeed seem once you migrate to the "cloud" backend then it's difficult to migrate again. You can't even migrate from the "cloud" backend on TFC to the "remote" backend on TFC:

> $ terraform init
> 
> Initializing the backend...
> Migrating from Terraform Cloud to backend "remote".
> ╷
> │ Error: Migrating state from Terraform Cloud to another backend is not yet implemented.
> │
> │ Please use the API to do this: https://www.terraform.io/docs/cloud/api/state-versions.html
> │
> │
> ╵

The suggestion then, with the benefit of hindsight, if you want to migrate from TFC to OTF, would be to stick with the "remote" backend if that's what you have and to migrate from that to OTF, before changing to the "cloud" backend.

**Comment by pat-s** [comment]
First: thanks for digging in so deep and caring about my issues :)

> Looks like your state upload error is a legitimate bug. OTF assumes state output values are strings, whereas they can of course being many things, including an array, which is what you have. I'll raise an issue. For now, you'll have to workaround it by ensuring all state outputs are strings. Sorry about that.

Ah, good to know in the first place that the error is not on my side and the migrate script I wrote actually works. Given that this is the second workspace I am migrating, I was probably just lucky then that the first one did not have non-string state outputs. As the amount of outputs is too high, I'll just wait for a fix on the OTF side before proceeding.

> And as you say, migrating from one "cloud" backend to another "cloud" backend, i.e. changing the hostname from app.terraform.io to your OTF hostname succeeds without error, but it neglects to migrate the state. I suppose TFC is only hosted on one hostname, app.terraform.io, and one would never need to perform this particular migration.

Yes, most probably.

> But that begs the question, how do people migrate state - when using the "cloud" backend - from Terraform Cloud to Terraform Enterprise, or vice-versa? I suspect your API-driven approach is unfortunately how they do it.

Yes, after a few days of dealing with it, I am also sharing this view.

> The suggestion then, with the benefit of hindsight, if you want to migrate from TFC to OTF, would be to stick with the "remote" backend if that's what you have and to migrate from that to OTF, before changing to the "cloud" backend.

Definitely. Unfortunately, I have 10+ workspaces already using the "cloud" backend. But once the Go error is solved, the script should do it. I think it's important to "save" future people to not "lock themselves in" with the "cloud" backend but suggest to migrate to the "remote" backend.

**Comment by pat-s** [comment]
So 0.0.30 makes the final state upload work 🎉 Hence my gist referenced above should work as is.

There are some post-upload steps required:

1. Deleting `.terraform` in the local workspace checkout (to get rid of the old TFC refs)
2. Running `terraform init` to sync the local state with the new remote counterpart
3. Success!

So overall my current view is like this: When coming from TFC, users **must** migrate their state via the API (see gist attached) to the `"remote"` backend:

```yml
  backend "remote" {
    hostname     = "<OTF_HOSTNAME>"
    organization = "<ORG>"

    workspaces {
      name = "<workspace name>"
    }
  }
```
