### ISSUE TITLE
Memory requirements

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#298]
What memory requirements are expected for OTF?

After installation memory was at 1.3 GB, now after a few runs in one workspace it went up to 3 GB.
Seems a lot given the base is written in GO 😨 

Restarting the pod and 

- 1 run: 560 MB
- 2 runs: 711 MB

Did you observe similar memory usage/fluctuations? Given that I only tried with one (small) workspace and a few runs, this seems quite a lot. I'd expect it to go way higher when more workspaces are present and multiple runs are triggered in parallel?

v0.0.26

**Comment by leg100** [comment]
The culprit might be the in-memory cache, caching config tarballs, logs, state files, plans, etc.

I do monitor the demo.otf.ninja cluster pretty closely. It's a three process cluster, and each process uses a pretty consistent 100MB *resident* memory, and roughly 1GB *virtual* memory. I take it you're reporting numbers for virtual memory? Even if you are, 3GB does sound like rather a lot. It could be harmless and the OS is merely allocating memory for caching files etc, that it can reclaim when it needs it. Or it could warrant further investigation.

I haven't performed any profiling nor load testing, and I would not be surprised if there are a few unclosed file handles and the like.

**Comment by pat-s** [comment]
> I take it you're reporting numbers for virtual memory? 

Yes. Though the reported values I was observing fluctuated a lot and I just used a k8s aggregation helper. I will move OTF to a single VM soon anyhow (as I need to disentangle the dependency on executing TF commands for our k8s cluster from the k8s cluster being operative). 
There I will have a more clear picture on the actual resource needs. 

Thanks for the `cache-size` pointer!

**Comment by pat-s** [comment]
A bit more observations here: I am running `otfd` on a VM (in docker) since some time (with remote agents on k8s). Whenever running a run on the VM, the OTF container increases in memory use a bit more.

I am running with `--cache-expiry 2m --cache-size 100` and would assume that a max of 100 MB is getting cached and after 2 mins the cache should be wiped again.
Indeed, I see a drop in memory after 2m, but it does not free all memory up to the state before the last run. This results in an increase between 50 - 100 MB for every run. At some point, my VM runs out of memory and I need to force reboot.

Is there something I am overlooking WRT to config? I don't see much more to control the memory consumption.

(The agents on k8s doesn't suffer from this and goes back to the memory usage it had before the run)

**Comment by leg100** [comment]
No, I don't think you're overlooking anything. It should "just work" out of the box (other than cache sizing...).

> At some point, my VM runs out of memory and I need to force reboot.

This is pretty serious, I think. Does the VM invoke the oom-killer (the "out-of-memory" killer, that starts killing processes to free up memory)?

**Comment by pat-s** [comment]
I see that the cache release works in general (i.e. I see a memory drop after the specified time). Though overall I see a little increase in mem which stays (with the container, i.e. otfd) and grows larger and larger over time. It might not be an issue of OTF etc., but triggered by something else/external. Just wanted to report it here since I can't wrap my head around this atm...

My current approach is to recreate the container once a day and hope that the VM survives until then 😅 

> Does the VM invoke the oom-killer (the "out-of-memory" killer, that starts killing processes to free up memory)?

I guess, at least, I have no ideas why it would not. It's a normal Ubuntu 22.04 VM.

**Comment by leg100** [comment]
Archiving repo.
