### ISSUE TITLE
BDD for E2E testing?

### ISSUE THREAD

**Issue by ghost** [leg100/otf#3]
Could a BDD framework like behave be used for E2E testing using the terraform binary? This would simplify creating & updating test cases, and would simplify testing with new versions of  the terraform CLI.

**Comment by leg100** [comment]
Could do, could do. Suppose you're talking about Ginkgo?

However, I think you can do a lot with the `testing` package and `go test`. Take a look at the e2e tests for a previous project of mine:

https://github.com/leg100/etok/tree/master/test/e2e

In tandom with [goexpect](https://github.com/google/goexpect) you can test both the stdout and stdin of a CLI program like terraform.

And the `testing` package has seen [improvements](https://dave.cheney.net/2020/03/10/go-test-v-streaming-output) that mean logs are streamed during a test rather than waiting for it to finish - particularly useful for long-running integration/e2e tests.

These things may not be mutually exclusive with something like Ginkgo. But I think it means we can eek out more mileage from `testing` before reaching for an additional lib just yet.

**Comment by fergalk** [comment]
Ginkgo would be the go equivalent, yeah.

The main advantage of using a BDD Framework is the ease of writing new test cases/modifying existing ones once you've built up a decent library; unless you're making a major change, it can usually be done without modifying any code. I've put together a quick demo to show this [here](https://github.com/fergalk/ots/tree/feature/bdd-framework/test/bdd); it's rough and ready & written in python but wouldn't be hard to rewrite in golang if you'd prefer to keep the project consistent.
The test case (there's only one currently) is defined [here](https://github.com/fergalk/ots/blob/feature/bdd-framework/test/bdd/features/terraform_workflow.feature), and you can select the version of the terraform cli used by the tests with a parameter [here](https://github.com/fergalk/ots/blob/feature/bdd-framework/test/bdd/behave.ini#L2).

Here's an example of a test run:
```
ergal@pop-os:~/code/ots/test/bdd$ behave 
Feature: Standard terraform user workflow # features/terraform_workflow.feature:1
Creating directory ./_tmp
Running command "tfenv install 1.0.0"
Terraform v1.0.0 is already installed
Command tfenv install 1.0.0 exited with code 0
Running command "tfenv use 1.0.0"
Switching default version to v1.0.0
Switching completed
Command tfenv use 1.0.0 exited with code 0
Starting local OTS server
Local ots server has been running for 5s, creating default organisation testorg
Organisation testorg created succesfully

  Scenario: run terraform init, plan, apply and destroy                                         # features/terraform_workflow.feature:2
    Given we are authenticated to the ots server                                                # features/steps/auth.py:6 0.000s
    When we run terraform command 'init' in directory './data/dummy_tf_module'                  # features/steps/terraform_command.py:6 1.415s
    Then the terraform command exit code is 0                                                   # features/steps/terraform_command.py:12 0.000s
    When we run terraform command 'plan' in directory './data/dummy_tf_module'                  # features/steps/terraform_command.py:6 1.439s
    Then the terraform command exit code is 0                                                   # features/steps/terraform_command.py:12 0.000s
    When we run terraform command 'apply -auto-approve' in directory './data/dummy_tf_module'   # features/steps/terraform_command.py:6 1.668s
    Then the terraform command exit code is 0                                                   # features/steps/terraform_command.py:12 0.000s
    When we run terraform command 'destroy -auto-approve' in directory './data/dummy_tf_module' # features/steps/terraform_command.py:6 1.676s
    Then the terraform command exit code is 0                                                   # features/steps/terraform_command.py:12 0.000s

1 feature passed, 0 failed, 0 skipped
1 scenario passed, 0 failed, 0 skipped
9 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m6.199s
```

You're right that the `testing` package can do everything that BDD can, I just find that once your project reaches a decent size traditional imperative test suites can become disorganised.

**Comment by leg100** [comment]
Looks really good Fergal, nice work. We'll revisit this once the project reaches that point of complexity. It's still early days but it's good to know what's possible. Thorough E2E tests are vital, particularly around the CLIs, which I want to be the main point of interaction for users.

**Comment by leg100** [comment]
Closing. The traditional imperative test suites are working very nicely.
