### ISSUE TITLE
Support for go-tfe only flow

### ISSUE THREAD

**Issue by fsaintjacques** [leg100/otf#301]
Greetings Louis, very nice project! I'd like to ask what's the flow when terraform-cli is completely avoided, i.e. we'd drive interaction to otf with a `go-tfe` client only and gitops:

- Workspace are created/deleted via server-side events, including a first initial plan & apply.
- Developers can trigger plan & apply via git events to a repository where the workspace are configured to pull the module

In such scenario, the programatic part of handling workspaces are *never* manually configured with `terraform-cli`, does otf supports server-side API tokens? I see that there are admin site token, but that seems a bit generous.

**Comment by leg100** [comment]
Hello and thank you. Yes, you can drive workflows via the API.

A good amount of the documented Terraform Cloud API is implemented. Indeed, a number of `go-tfe` integration tests are invoked as part of the build pipeline, to validate the implementation. 

I must warn you though that support is not 100%. For instance, you cannot configure the workspace to pull from a git repo via the API, only via the web UI. I've opened an issue to fix this: #302. You can, however, create/delete workspaces, and create plans and applies via the API.

API tokens: yes, users can create API tokens. Go to your user profile in the top right corner of the web UI and you'll see a link to the tokens menu. Team and organization API tokens are not yet available. Let me know if this is something you would like.

**Comment by fsaintjacques** [comment]
Thank you for the quick response, we would indeed need the following:

1. Create a workspace pointing to a git repo via API.
2. Have organization keys for automation. I'd like to avoid binding keys to users in order to decouple users/developers lifecycle with production environment.

The first one has a much higher priority from my POV. I will probably prototype with otf to see if it can fit my requirements.
