### ISSUE TITLE
Workspace can only be connected to VCS from same user that created personal access token

### ISSUE THREAD

**Issue by nokernel** [leg100/otf#303]
Even if you are admin, you can't connect a workspace to a VCS that was done using another user's personal access token.

With error

```2023-02-20T15:28:11Z ERR connecting workspace | error="registering webhook connection: POST https://api.github.com/repos/Optable/optable-terraform/hooks: 404 Not Found []" repo=[redacted] subject=[redacted] workspace=ws-[redacted]```

This is problematic as one user that setup a VCS can't leave the company otherwise you will break the otf workspace integration with.

**Comment by leg100** [comment]
Hello, I can't replicate the problem you're seeing. These are the steps I'm performing:

As me (leg100):
1. Go to 'VCS providers' in organization main menu
2. Click 'New Github VCS Provider'
3. Create personal access token on github.com and paste into form and click 'Create VCS Provider'
4. VCS provider created.

As site admin:
5. Select a workspace in same organization
6. Click 'Connect to VCS' in workspace settings
7. Select VCS provider
8. Select repo
9. Connected.

From the error message you've provided it looks like you're getting to at least step 8 and you're being presented with a list of repositories. Is that correct? Because that would mean you're successfully using the VCS provider token to at least retrieve the list of repositories. Yet when it comes to creating the webhook - which occurs as part of step 9 - you're receiving a 404, which is strange. If you didn't have permission I would expect it to return a 403 (forbidden).

Silly question: are you double sure the repo exists?

**Comment by nokernel** [comment]
> Hello, I can't replicate the problem you're seeing. These are the steps I'm performing:
> 
> As me (leg100):
> 
>     1. Go to 'VCS providers' in organization main menu
> 
>     2. Click 'New Github VCS Provider'
> 
>     3. Create personal access token on github.com and paste into form and click 'Create VCS Provider'
> 
>     4. VCS provider created.
> 
> 
> As site admin: 5. Select a workspace in same organization 6. Click 'Connect to VCS' in workspace settings 7. Select VCS provider 8. Select repo 9. Connected.
> 
> From the error message you've provided it looks like you're getting to at least step 8 and you're being presented with a list of repositories. Is that correct? Because that would mean you're successfully using the VCS provider token to at least retrieve the list of repositories. Yet when it comes to creating the webhook - which occurs as part of step 9 - you're receiving a 404, which is strange. If you didn't have permission I would expect it to return a 403 (forbidden).
> 
> Silly question: are you double sure the repo exists?

Answer to question 1 : Yes when I am at step 8 I see the list of repo of the VCS provider, that is correct.

Answer to question 2 : Yes the repo exist.

The diff here is that I created the VCS provider as site admin with the other user personal token, since I do not want to grant admin access to.

I have the otf github bot user with a personal access token, and read-only access to one terraform repo.

Then with my OTF admin user I added that bot user's personal access token into OTF web interface, this might be where the issue kicks in.

**Comment by leg100** [comment]
> I have the otf github bot user with a personal access token, and read-only access to one terraform repo.

Ah, this might well be the problem. The user needs to have permission to create a webhook on the repo, which according to [1] requires the admin role. Again, I'm not sure why Github is returning 404 when it should be returning 403 forbidden. If lack of permissions is indeed the problem, could you try using a token with a user that has the admin role?

[1]: https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization

**Comment by nokernel** [comment]
> > I have the otf github bot user with a personal access token, and read-only access to one terraform repo.
> 
> Ah, this might well be the problem. The user needs to have permission to create a webhook on the repo, which according to the [docs](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization) requires the admin role. Again, I'm not sure why Github is returning 404 when it should be returning 403 forbidden. If lack of permissions is indeed the problem, could you try using a token with a user that has the admin role?

Ah interesting, did I miss something in the doc?

Meanwhile I will re-try with admin role on the repo for that user to see if that works.

**Comment by nokernel** [comment]
Alright, you are very right, so any user that can configure workspace with vcs provider must be admin on the vcs.

Not sure I like this situation, I need to think about it.

**Comment by leg100** [comment]
> Ah interesting, did I miss something in the doc?

No, no you didn't. A note needs adding to the docs.

> Alright, you are very right, so any user that can configure workspace with vcs provider must be admin on the vcs.

A VCS provider must be created with a personal access token from a Github account with admin role privileges. When you use that account to generate the token, you specify the 'repo' scope, limiting what you can do with the token. That's if you choose to generate a *classic* personal access token. I notice there is beta support for *fine-grained* tokens, which let you restrict permissions further still, for instance only to allow managing webhooks.

As for connecting a workspace to a VCS repo, only the site admin and members of the owners team can do that. Anyone in a team with the 'manage workspaces' organization-level permission, or with the 'admin' workspace-level permission should be able to do that too. In theory, with these permissions you do in effect also receive all the privileges of the personal acess token, insofar as the OTF lets you use the VCS provider for that token, e.g. for connecting workspaces and modules to VCS repositories, but in practice you cannot do anything more. OTF does not give you access to the token itself.
