### ISSUE TITLE
`git` missing in images?

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#323]
Currently testing 0.0.30 for state migration reasons etc. (which seems to have worked! 🎉 ) but getting a (new) error when running a plan:

```
│ Could not download module "<some name>"
│ (security_groups.tf:112) source code from
│ "git::https://github.com/terraform-aws-modules/terraform-aws-security-group?ref=v4.16.2":
│ error downloading
│ 'https://github.com/terraform-aws-modules/terraform-aws-security-group?ref=v4.16.2':
│ git must be available and on the PATH.
```

Running plans worked in the previous versions. Though even when trying to revert until 0.0.26, I keep getting the same error.

Manually installing git in the running container (`apk add git`) makes subsequent plans work.
Yet I wonder what has changed given that it worked before for me on the same VM instance (running also in docker).

**Comment by leg100** [comment]
No, I think you're right, a missing `git` binary is the cause. I have seen this error before but neglected to raise an issue.
