### ISSUE TITLE
Manually deleting GH webhooks prevents a workspace from VCS disconnect

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#324]
I was just doing some troubleshooting WRT to webhooks and deleted the GH webhooks manually from the repo. Afterwards I wanted to disconnect the workspace within OTF from the GH repo. This failed with

```
DELETE https://api.github.com/repos/<org>/<repo>/hooks/402876696: 404 Not Found []
```

which makes sense as the WH does not exist anymore. Yet I cannot disconnect the repo anymore and hence not reconnect it. 

Proposal to handle this situaton:
1. print a warning message to the user that the WH is not being found
2. force disconnect the workspace from the repo

Given that a workspace has a state, deleting and creating a new one is not always a "simple" solution.

**Comment by leg100** [comment]
Emminently sensible. Failure to remove a webhook should not fail the transaction; it's more a housekeeping measure than an imperative step.
