### ISSUE TITLE
Dynamic agents

### ISSUE THREAD

**Issue by hoshsadiq** [leg100/otf#332]
It would be nice to be able to provision agents dynamically, e.g. when running on Kubernetes, docker, or other system. Assuming the config is there, what otf would do is create a new a pod/container that runs the agent. The agent would exclusively execute the run it was spun up for, then otf will shut the agent down after it has finished its run. Optionally, plan and apply would spin up different agents to avoid having long-running containers that could potentially be killed depending on the underlying container environment.

This deviates from what TFE does, however, I don't think otf should be limited to TFE functionality.

This system should probably be limited to container systems (Kubernetes, Docker, ECS, etc), as they usually have simpler APIs and are much faster to provision applications compared to VMs. This also keeps the scope minimal.

I think having a pluggable system would be ideal, in that, OTF provides some interfaces that can then be plugged by individuals through subpackages.

**Comment by leg100** [comment]
OTF's predecessor, [etok](https://github.com/leg100/etok), did just that. It spins up a pod for each run. I decided in the end a kubernetes operator - which etok is - was not the right approach. I drew a number of lessons from that experience, mostly forgotten admittedly. I vaguely recall it wasn't as straightforward to interact with a pod as it is with a forked process, which is how OTF executes terraform. And it takes a couple of seconds for a pod to spin up; but I understand not everyone minds that.

May I ask what the motivation is?

**Comment by hoshsadiq** [comment]
I guess I'm thinking about the automation side of things.

I was just playing around with otf and trying to set it up through docker-compose. However, adding agents is a very manual process, so it is not possible to do something like `docker-compose up -d --scale agent=2` or something like that.

Having otf handle agents also allows for dynamic scaling of underlying resource usages as opposed to have the agents run 24/7.

**Comment by leg100** [comment]
Well, if you're happy for agents to share an agent token there's nothing to stop you spinning up N agents via docker-compose. It shouldn't be a particularly manual process beyond that.

And of course you can spin up N `otfd` instances, scaling them up and down if you so wish.

TFC agents do have a "one shot" mode, whereby they handle one run then exit. Not sure if that's something that would help if OTF adopted it for its agents too.

Ultimately, I don't think I see any advantage to what you're suggesting if you're spawning agents on the same host. But what you're suggesting makes sense on a multi-host system like a kubernetes cluster: `otfd` would receive a request to create run, it would then invoke the run within a pod. Kubernetes would then take care of finding sufficient resources to run the pod, scaling out if necessary. Does that make sense?

**Comment by fsaintjacques** [comment]
Isn't that what kubernetes jobs are? It would be neat if otf supported spawning runs via kubernetes jobs.

**Comment by leg100** [comment]
Archiving repo.
