### ISSUE TITLE
Run not releasing workspace lock

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#334]
Getting the following error in one of my workspaces

```
2023-03-06T13:08:47Z ERR unlocking workspace | error="workspace locked by different user" subject=pat-s workspace=ws-dcyXbpdM5Ms5RRKG
```

I only have two users so far:
1. site-admin
2. pat-s (via GH)

Yet I cannot unlock with both of them. I wonder, which user has the lock?

Also interesting: despite the lock, I can still trigger runs in the UI.

I think it could help if 

- the user having the lock is displayed
- the lock ID is displayed to one can use `terraform force-unlock` on it

**Comment by leg100** [comment]
Hover over the lock status like so:

> ![image](https://user-images.githubusercontent.com/75728/223124790-6aded48c-dd2c-4687-81d7-b9528b48ba06.png)

Could be made more obvious, but you've probably noticed I'm not a UI guy...

Regardless, sounds like there are further issues with locks. Let me know what you find out.

**Comment by leg100** [comment]
Still being able to trigger runs: are they speculative runs, i.e. plan-only runs? Because they are still permitted on a locked workspace.

**Comment by pat-s** [comment]
Thanks! Didn't catch the hover. It also takes some time to appear. 

![image](https://user-images.githubusercontent.com/8430564/223135769-aab1f4de-67ca-4f5b-bcec-bf2c4d02554b.png)

> Could be made more obvious, but you've probably noticed I'm not a UI guy...

Oh no issues for me, I am more focused on the features :)

> Still being able to trigger runs: are they speculative runs, i.e. plan-only runs? Because they are still permitted on a locked workspace.

I can still also run applies, i.e. there is no real effective lock. Look more like a stuck lock display right now.

But fortunately it just resolved itself somehow while I was writing this reply (after being in that state for some time/runs), so I guess it might have just been a temporary hickup. 

Sorry for the noise and thanks again for the quick reply!

**Comment by pat-s** [comment]
Oh, just now I got into the same situation again.

Having a lock from a specific run (5 runs into the past, and the run succeeded). And now follow-up runs are waiting on that run to finish (and most likely to release the lock), but it doesn't. And I can't see how I can force-unlock 🤔

**Comment by pat-s** [comment]
I think what I would need is a "force unlock" option in the UI which is not being blocked by the lock of another user. Maybe restricted to the "site admin" user. Right now I don't see how I can get out of the lock state again.

**Comment by leg100** [comment]
What's the status of the run that holds the lock?

I'll add a force unlock button to the UI.

**Comment by pat-s** [comment]
![image](https://user-images.githubusercontent.com/8430564/223154627-39e464db-0d89-470c-bca9-d21613aeb6dc.png)

That's the one of the current lock (different from the one above). It went through normally but it seems to not have released the lock for some reason.

> I'll add a force unlock button to the UI.

Awesome, thanks!

**Comment by leg100** [comment]
Closing:

* OTF now supports `terraform force-unlock <organization>/<workspace>`. This works precisely the same way as TFC.
* As for the UI button, if a workspace is locked:
  * The UI will show an "unlock" button if the user is the same user holding the lock
  * Otherwise, if the user has permission, the UI shows a "force unlock" button
  * Otherwise, shows an "unlock" button but it is greyed out.
  * In all cases hovering over the lock status will show a tooltip indicating who/what has locked the workspace.
