### ISSUE TITLE
Some runs are pending forever | waiting for previous runs

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#338]
- new repo, fresh state
- GH VCS
- v0.0.31

Some runs executed just fine. Then, without any particular change I can see so far, some runs are just pending forever. I see they were triggered successfully without any errors

```
2023-03-11T16:38:18Z INF finishing phase | component=agent phase=plan run=run-zSxOBcWKMcZtBXxN
2023-03-11T16:38:18Z INF finished plan | additions=0 changes=0 destructions=0 id=run-zSxOBcWKMcZtBXxN subject=local-agent
2023-03-11T16:45:21Z INF canceled run | id=run-dTXe0R6h9SxjagHX subject=pat-s
2023-03-11T16:45:29Z INF triggering run | component=triggerer hook=b351c19b-8dd5-41b4-af10-1582bdc6998a
```

Though they are just never starting

![image](https://user-images.githubusercontent.com/8430564/224497175-bcb94957-6391-429d-ad0a-347f4c22d930.png)

Canceling and triggering a new run locally I see that it seems some previous runs are stuck

```
 tf apply
Running apply in the remote backend. Output will stream here. Pressing Ctrl-C
will cancel the remote apply if it's still pending. If the apply started it
will stop streaming the logs, but will not stop the apply running remotely.

Preparing the remote apply...

To view this run in a browser, visit:
https://$HOST/app/$ORG/$REPO/runs/run-9mdrF9k7bOCfOTFf

Waiting for 3 run(s) to finish before being queued...
```

even though in the UI all report that they finished in some way

![image](https://user-images.githubusercontent.com/8430564/224497697-1d061899-1b05-42c6-b4d3-ee647e4bb456.png)

**Comment by pat-s** [comment]
I somehow got out of it again and couldn't directly reproduce but there seems to be some kind of hickup in certain sequences of triggering runs 🤔

**Comment by leg100** [comment]
I've noticed the same transient behaviour. We'll keep this issue open until it is resolved. If I see the same behaviour again on my side I'll perform some root-cause-analysis. Failing that, some load tests should re-produce it.

**Comment by leg100** [comment]
Closing because I haven't witnessed this behaviour for a while.

**Comment by pat-s** [comment]
I've just encountered this behavior again. There are no other runs which the run could be waiting for. 

![image](https://github.com/leg100/otf/assets/8430564/883294de-ee2c-42b9-8832-ea76952c9b16)

I don't see any help in the logs, not even a reference to the pending run. If you have any idea how I could track this down in more detail, let me know.
