### ISSUE TITLE
FR: Overview of last workspace runs in overview

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#339]
TFC shows a nice green/redge badge indicating the status of the last runs of a particular workflow.
This gives a good overview of the overall status of all workspaces.

Maybe something similar could be added to the workspace overview in OTF? Currently one needs to enter a specific workspace to see the status of the latest run.

**Comment by leg100** [comment]
Sounds like a good idea. The UI is currently pretty bare. A lot of information is potentially available so it's not a lot of work to 'surface' it to the web UI.
