### ISSUE TITLE
FR: Projects

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#340]
via folders or tags. Helps to stay organized with many workspaces.

**Comment by leg100** [comment]
I noticed TFC recently introduced 'projects' which performs this role. Probably not a high priority but we'll keep this issue open until implemented.

**Comment by fsaintjacques** [comment]
Correct, I would rename this issue as support for Projects.

**Comment by leg100** [comment]
> Correct, I would rename this issue as support for Projects.

Done.
