### ISSUE TITLE
Failed to upload configuration files: Unprocessable Entity

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#415]
In some workspaces I get the following error when executing local `terraform` commands.

The workspaces are not particular "big", even though this is of course a subjective statement.

I thought of a proxy issue but all proxy-related upload settings I am aware of are actually set to allow higher limits.
I also haven't encountered these issues in previous versions, so maybe it's also OTF related?

Anyhow, maybe you've come across this also at some point and have an idea? Maybe its related to terraform?

```
tf plan
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

╷
│ Error: Failed to upload configuration files: Unprocessable Entity
│ 
│ config exceeds maximum size (10485760 bytes)
│ 
│ The configured "remote" backend encountered an unexpected error. Sometimes this is caused by network connection problems, in which case
│ you could retry the command. If the issue persists please open a support ticket to get help resolving the problem.
```

**Comment by leg100** [comment]
The clue is in the error message :)

Set this flag accordingly:

```
      --max-config-size int            Maximum permitted configuration size in bytes. (default 10485760)
```

**Comment by pat-s** [comment]
Ah thank you! Didn't know I can/need to set this specifically.
