### ISSUE TITLE
Bundling `helm-git` in images?

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#416]
I am using https://github.com/aslafy-z/helm-git frequently and for that always have to switch to "local only execution" as the binary is not bundled within the OTF image.

I could ofc post-install or build my own images but I was just wondering if there might be the possibility to include it within the official images by default?

**Comment by leg100** [comment]
I don't think it's quite sufficiently fundamental to qualify for inclusion into the official image. Most people probably won't be using this.

Do you use `helm-git` as part of a terraform plan/apply? I'm looking to possibly provide the option to instead run terraform within a docker container, and you could have the option to supply the image to use for these operations.

**Comment by pat-s** [comment]
I agree that it depends on people's workflows and dev focus though `helm-git` is quite "popular" and arguably quite small in size.

The overhead of building my own images for this is somewhat high in contrast. But I can certainly understand your decision/reasoning.

> Do you use helm-git as part of a terraform plan/apply? 

Jup, in my dev environment, whenever I want to test HEAD of a repo and still reuse my existing TF config with all sensitive mappings etc.

> I'm looking to possibly provide the option to instead run terraform within a docker container, and you could have the option to supply the image to use for these operations.

**Comment by pat-s** [comment]
I've set up a build matrix which adds `helm-git` to the OTFD images. Works fine so far.

[cynkra/otfd](https://hub.docker.com/repository/docker/cynkra/otfd/general)
