### ISSUE TITLE
FR: Support plan-only runs on push events for non-default branches

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#418]
derived from https://github.com/leg100/otf/issues/395#issuecomment-1525830609

**Comment by leg100** [comment]
Again, if I understand the title of the PR correctly, OTF already does this. Any commit to a non-default branch triggers a speculative plan, i.e. a plan-only run.

**Comment by pat-s** [comment]
Thanks. I just tried this again explicitly and for me no run was triggered when pushing to a non-default branch of a VCS workspace.

OTF 0.0.38

**Comment by leg100** [comment]
Ok, so I stand corrected. A commit to a non-default branch will currently only trigger a run if the commit is part of an open PR. You would like commits to non-default branches that not part of a PR to trigger a run.

I will see what I can do with this. Currently, I'm prioritising work that aligns with TFC, and I'm not sure TFC supports what you're requesting.

**Comment by pat-s** [comment]
Thanks. Rethinking this, auto-runs on PRs only are fine if there would be the option to trigger runs in the UI for non-default branches (#417). Otherwise I am always required to open a PR to trigger a plan automatically. I know I can do it via the CLI and it will be streamed but just thinking of my preferred CLI <-> UI relationship.

**Comment by leg100** [comment]
Archiving repo.
