### ISSUE TITLE
FR: Pagination: changing items per page

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#425]
Would be great if this would be configurable or if pagination could be turned off entirely. Makes it easier to search for workspaces as one does not need to find the matching page in the workspace overview.

Tags help already (and I like it!) but I think this could be a nice addition with maybe not too much effort?

Thanks for your work again! 🚀

**Comment by leg100** [comment]
Changing items per page is certainly doable. We'll keep this issue open until that's done.

As for turning it off entirely, that might take a lot more work. Instead I think adding a search box to the workspace listing page might be a better approach.

**Comment by pat-s** [comment]
Ah sure, whatever is easier or more liked by you. In the longterm a search functionality is certainly a more professional solution but maybe not so trivial to implement.

**Comment by leg100** [comment]
Note: #461 adds search and sets the number of items per page to 100 rather than 10. I thought that was better than permitting the user to configure a specific number of items per page.
