### ISSUE TITLE
OIDC: required scopes

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#443]
Just tried out OIDC login via https://docs.otf.ninja/latest/auth/providers/oidc/

I noticed the information about required scopes is missing. When trying with Keycloakx (our SSO IDP), I noticed OTF requires a custom scope `groups` which must first be created and is not a default scope.

I think the docs should list the required scope and maybe also mention that `groups` is not a pre-existing scope in all IDP providers.

Scopes requested: `openid+groups+profile`

**Comment by leg100** [comment]
Thanks for raising the issue, I've raised a PR.

(The `groups` scope/claim is not actually current used, but it probably will in future, to provide authorization, so I've documented it as required).
