### ISSUE TITLE
Just to show my admiration

### ISSUE THREAD

**Issue by Spritekin** [leg100/otf#449]
Hi @leg100 

This is just to express my most profound admiration on your project. I'm not planning to use it for now but I really really love it.

Kudos.

Regards,

**Comment by leg100** [comment]
G'day Spritekin, thank you, you're too kind.

Out of interest, what is it you like about it? Even in general terms it would help to know.

**Comment by Spritekin** [comment]
Sure,

I have been doing DevOps and Infrastructure Management and platform architecture for many years using different technologies, languages, tools, etc.

Terraform got into me about 5 years ago and while it was interesting I found the implementation process suggested in many places lacking in one or other area, like nobody really agreed on the best way to do stuff. Most solutions just complicate the cleanliness of the terraform code and module reusability.

Then I modelled my CI/CD methodology but found the most adequate provider to represent what I had in mind was Terraform Cloud. For a proper IaC I really need a SaaS that provides me with a solid infrastructure provisioner, I evaluated many other providers (Spacelift, Scalar, etc) from cost/benefit perspective as well and I found TFC was the best match for my needs (modules, workspaces, it was a clear fit).

However TFC is still not the best case, if you have multiple events in your queue then you really need multiple agents and TFC (even in their new plans) won't let me do more than 2 agents and for continuous build events it becomes a bottleneck. In addition, I have painted myself to a corner as TFC became my best match it is hard to move away from it thus violating my "design with loose coupling" IT principle. I'm essentially at the whims of Hashicorp business plans. I could go to other providers (i.e. Scalr) but pricing wise is not cost effective.

Then comes your OTF and it just breathe life to my design. Suddenly I have the ability to use TFC as my low level resource management allowing me to build the infrastructure enough to install OTF as the real resource manager which provides me with full control of agents, no longer with the bottleneck I had and with the ability to move away anytime. A real life saver that might shake all competition if properly shared.

As I mentioned, I'm not ready to adopt OTF right now I feel it has to mature the APIs a bit more (looking at the ticket on creating a workspace with a git source via API) but I'm seriously considering OTF for my next project.

So that's it, you have a valuable tool there. I will talk to you about it in the future for sure.

Best wishes,

**Comment by leg100** [comment]
Thank you for the background @Spritekin.

As it happens, the issue you refer to, #302, the requested functionality was implemented a while ago. I don't close such issues until I have a test covering them and I'll only close that once a suitable integration test is in place. 

But your general feeling is correct: you will inevitably find quite a few rough edges in addition to API endpoints that are yet to be implemented.

Thanks again for the kind words.
