### ISSUE TITLE
Custom images: how to set `footer-version` correctly?

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#450]
In the custom images I am building I always get "unknown" for the footer version.

Can you give me a hint which build process I might be missing that defines the version in the image? I searched and found it in the HTML template but I can't infer why the build is not picking it up correctly.

![image](https://github.com/leg100/otf/assets/8430564/71337f1e-1cf6-49b2-9684-e437849b6639)

**Comment by leg100** [comment]
You've caught a legitimate error! The regression occured when I moved packages around a week or two ago.

Fix will appear in next release: https://github.com/leg100/otf/commit/21dfac4a591546936c88c5c72e9921ec93346ae6
