### ISSUE TITLE
`caching configuration version tarball: entry is bigger than max shard size`

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#452]
Getting this error in of my repos when trying to trigger a "plan" build from the UI

![image](https://github.com/leg100/otf/assets/8430564/28270868-804f-4130-8209-4191898f431b)

OTF is running with `--max-config-size 104857600 --cache-expiry 2m --cache-size 1500` (v0.0.43)

**Comment by leg100** [comment]
Hello. I've added a fix:

3b3ece4df6b3082d3c7bad1b18162f924fc6ca02

For some reason, the max cache size was being divided by the number of "shards", which in this defaults to 1024, therefore your max cache size was actually being set to:

```
1500 / 1024 = 1.46484375 MB
```

The fix will be in the next version (v0.0.45).
