### ISSUE TITLE
"cannot upload config for a configuration version with non-pending status"

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#453]
I am seeing the following error message in one of my workspaces with "remote" execution when triggering a build locally

```
ERROR uploading configuration error="cannot upload config for a configuration version with non-pending status: uploaded"
```

Same workspace as for #452 so might be related

**Comment by leg100** [comment]
Highly likely to be related. I'll keep this one open because this should not happen regardless. I might make a failure to cache a config tarball a non-fatal error, which I think would solve this particular issue.
