### ISSUE TITLE
API start first run with VCS provider

### ISSUE THREAD

**Issue by Spritekin** [leg100/otf#473]
Hi,
I used the API to create a workspace linked to a VCS. I know it works because if I go to the UI and start a run, it starts just fine and the run finishes.

However, if I start the FIRST run run via the API it complains there is no configuration version:
```
2023/06/20 12:06:30 DEBUG received vcs event id=261e70cb-bb10-4e21-bc9f-40d1bc04dfbd repo=spritekindev/oss-user-otf cloud=github
2023/06/20 12:06:38 DEBUG-8 retrieved user username=Spritekin subject=auth
2023/06/20 12:06:38 DEBUG-8 retrieved workspace subject=Spritekin workspace=ws-8aY1wPYb1zf1qmFz
2023/06/20 12:06:38 ERROR retrieving latest configuration version error="resource not found" workspace_id=ws-8aY1wPYb1zf1qmFz subject=Spritekin
2023/06/20 12:06:38 ERROR constructing new run error="resource not found" subject=Spritekin
```

And the first run is not created.

So I create a configuration version using the API and I can see in the logs:
```
2023/06/20 12:24:30 DEBUG created configuration version id=cv-3X1EdEO2mVwBfrj1 subject=Spritekin
```

Then I try to run again and I get:
```
2023/06/20 12:24:40 DEBUG-8 retrieved latest configuration version workspace_id=ws-gpFVGhg1gupjEvg4 subject=Spritekin
2023/06/20 12:24:40 DEBUG created run id=run-mtqmuUbf6qwPsZaX workspace_id=ws-gpFVGhg1gupjEvg4 subject=Spritekin
2023/06/20 12:24:40 DEBUG-8 retrieved configuration version id=cv-3X1EdEO2mVwBfrj1 subject=reporter
2023/06/20 12:24:40 DEBUG locked workspace subject=run-mtqmuUbf6qwPsZaX workspace=ws-gpFVGhg1gupjEvg4
2023/06/20 12:24:40 INFO enqueued plan id=run-mtqmuUbf6qwPsZaX subject=scheduler
2023/06/20 12:24:40 DEBUG-8 retrieved configuration version id=cv-3X1EdEO2mVwBfrj1 subject=reporter
2023/06/20 12:24:40 INFO started plan id=run-mtqmuUbf6qwPsZaX subject=local-agent
2023/06/20 12:24:40 DEBUG-8 retrieved workspace subject=local-agent workspace=ws-gpFVGhg1gupjEvg4
2023/06/20 12:24:40 DEBUG-1 created run token subject=local-agent !BADKEY=run
2023/06/20 12:24:40 DEBUG-8 listed variables subject=local-agent workspace_id=ws-gpFVGhg1gupjEvg4
2023/06/20 12:24:40 INFO executing phase component=agent run=run-mtqmuUbf6qwPsZaX phase=plan
2023/06/20 12:24:40 DEBUG-8 downloaded configuration id=cv-3X1EdEO2mVwBfrj1 bytes=0 subject=local-agent
2023/06/20 12:24:40 DEBUG-8 retrieved configuration version id=cv-3X1EdEO2mVwBfrj1 subject=reporter
2023/06/20 12:24:40 DEBUG-2 written logs id=run-mtqmuUbf6qwPsZaX phase=plan offset=0
2023/06/20 12:24:40 DEBUG-2 written logs id=run-mtqmuUbf6qwPsZaX phase=plan offset=73
2023/06/20 12:24:40 ERROR executing phase component=agent run=run-mtqmuUbf6qwPsZaX phase=plan error="1 error occurred:\n\t* unable to unpack config: failed to decompress archive: EOF\n\n"
```

Now, the UI shows the run as errored, but it still counts as a first run so from then on any change in the VCS code triggers a new run as expected.

So all in all it works, but it is annoying to see the first run as an error. I guess I could rerun from the API, not ideal but it works.

**Comment by Spritekin** [comment]
P.S. Sarting a second run via API didn't work. However changing the source code in the VCS starts a new run and it succeeds. I'm happy with that. Annoying but ok.

**Comment by leg100** [comment]
So this is working as expected. When you create a run via the API the workspace must first have at least one configuration version. This behaviour is the same as TFC.

Yes, on the second attempt you do create a configuration version but you neglect to then _upload_ the tarball. Hence the error regarding an `EOF` when unpacking the tarball. (Maybe this error should be improved).

See the TFC document regarding an [API-driven run workflow](https://developer.hashicorp.com/terraform/cloud-docs/run/api).

You might expect that for a VCS connected workspace, creating a run via the API would automatically use the config version from the VCS repo. By default, that's not how OTF nor TFC behaves, and this behaviour is only followed when commits are pushed to the repo and the webhook is triggered. But interestingly another user ran into this same issue and wanted this exact behavour for the API. So I implemented a "magic string", which is specified in place of the configuration version ID when creating a run via the API, will trigger this very behaviour. It was only implemented last week:

https://developer.hashicorp.com/terraform/cloud-docs/run/api#5-upload-the-configuration-content-file

Let me know how you get on.

**Comment by Spritekin** [comment]
Right, I has probably being spared from this complexity by the Terrasnek library.
Then the work is...
a. Create the configuration version.
b. Get the upload path.
c. Tar the contents of my VCS.
d. Upload the tar to the upload path.
e. Start the run.

But then my question is... if I have to do al this work, why do I need to connect to the VCS at all?

**Comment by Spritekin** [comment]
After checking Terrasnek, I have to say I'm confused. Terrasnek just calls the TFC runs API and submits my create run payload and the run starts. I never had to upload a configuration tar for this to work.
Terrasnek code for the create run API is like this:
```
    def _create(self, url, payload=None):
        """
        Implementation the common create resource pattern for the TFC API.
        """
        if payload is None:
            payload = {}

        return self._post(url, data=payload)

     def create(self, payload):
        """
        ``POST /runs``

        `Runs Create API Doc Reference \
            <https://www.terraform.io/docs/cloud/api/run.html#create-a-run>`_

        `Create Sample Payload \
            <https://www.terraform.io/docs/cloud/api/run.html#sample-payload>`_
        """

        return self._create(self._runs_api_v2_base_url, payload)
```

So no fancy stuff... just take my payload and send to th /runs API.

My payload follows the workspace run creation like:
```
    payload = {
      "data": {
        "attributes": {
          "message": "First run",
          "auto-apply": True
        },
        "type":"runs",
        "relationships": {
          "workspace": {
            "data": {
              "type": "workspaces",
              "id": workspace_id
            }
          }
        }
      }
    }
    run = tfc.runs.create(payload)
```

So nothing funky and I know it works I have been using this in TFC for a few months now. Workspace was created using this payload:
```
          "data": {
            "attributes": {
              "name": workspace_name,
              "auto-apply": True,
              "resource-count": 0,
              "terraform_version": "1.3.0",
              "trigger-patterns": ["/trigger.tf"],
              "vcs-repo": {
                "identifier": "spritekindev/%s" % (workspace_name),
                "oauth-token-id": args.tfcgithubprovider,
                "branch": ""
              }
            },
            "type": "workspaces"
          }
        }
```
Again nothing weird. And I can trigger the runs anytime. So not sure what is going on.

**Comment by Spritekin** [comment]
Is there any way I can help with this one?
