### ISSUE TITLE
Error when building from source

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#488]
I am getting the following build error when building in my CI lately. Issue might be (most likely) on my side since we've moved to a new CI. 

However, I have no idea what might be wrong - actually the building is happening using `golang:1.20-alpine` and hence I would assume that it works anywhere...

Do you have any idea what might be missing/wrong? My golang knowledge is not sufficient enough here to solve it :/

The build was running on https://github.com/leg100/otf/commit/6edd315437c517a8e132df82fd3a6d2aba326c44

```
make build

# github.com/leg100/otf/internal/pubsub
internal/pubsub/marshaler.go:61:3: unknown field Event in struct literal of type pgevent
internal/pubsub/marshaler.go:62:3: unknown field Payload in struct literal of type pgevent
internal/pubsub/marshaler.go:67:25: undefined: notificationMaxSize
internal/pubsub/marshaler.go:75:4: unknown field Event in struct literal of type pgevent
internal/pubsub/marshaler.go:76:11: cannot use &id (value of type *string) as string value in struct literal
internal/pubsub/marshaler.go:93:17: invalid operation: event.ID != nil (mismatched types string and untyped nil)
internal/pubsub/marshaler.go:99:56: invalid operation: cannot indirect event.ID (variable of type string)
internal/pubsub/marshaler.go:115:34: event.Payload undefined (type pgevent has no field or method Payload)
internal/pubsub/marshaler.go:123:18: event.Event undefined (type pgevent has no field or method Event)
```

**Comment by leg100** [comment]
Looks like a problem with your checkout, there is no `internal/pubsub/marshaler.go` in that commit.

**Comment by pat-s** [comment]
Most likely, I am doing some non-interactive git merge up your upstream changes into my branch. Will have a closer look at this part then, thanks :)
