### ISSUE TITLE
Question: Install aws cli?

### ISSUE THREAD

**Issue by Spritekin** [leg100/otf#498]
I'm not sure how to proceed on this one. When running a Terraform module that requires Kubernetes, I use the AWS CLI to connect to EKS (aws eks get-token) but apparently the aws cli is not part of otf then it fails:
```
│ Error: Post "https://9235208A1234516DFF6ECFEF6471E27.gr7.ap-southeast-2.eks.amazonaws.com/api/v1/namespaces": getting credentials: exec: executable aws not found
```
So I understand I might need to create my own image with AWS CLI installed. Is there any "official" solution for this?

**Comment by leg100** [comment]
No official solution. It is as you say, build an image with whatever tools you want. I'd recommend using `leg100/otfd` as a base image. That seems the most elegant solution. The same applies to the agent image, `leg100/otf-agent`, if you're using that.

**Comment by fsaintjacques** [comment]
Isn't that provided in the aws provider?

**Comment by Spritekin** [comment]
@fsaintjacques 
yes but no. let me give you an example. This is a typical kubernetes provider initialisation.

```
data "aws_eks_cluster" "cluster" {
  name = local.cluster_name
}

data "aws_eks_cluster_auth" "cluster" {
  name = local.cluster_name
}

## Connect to the cluster
provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority[0].data)
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    args        = ["eks", "get-token", "--cluster-name", local.cluster_name, "--role-arn", var.kubernetes_access_role ]
    command     = "aws"
  }
}
```

Look that the authentication token is obtained by running an "aws eks get-token" command using the AWS CLI. If the AWS CLi does not exist in the running container, the command fails as:
```
kubernetes_namespace.noss-prod: Creating...
│ Error: Post "https://9235208A204D3616DFF6ECFEF6471E27.gr7.ap-southeast-2.eks.amazonaws.com/api/v1/namespaces": getting credentials: exec: executable aws not found
```

So we would need the AWS CLI in the container. The same would happen with some other tools I guess... or maybe if you don't have a provider and want to use Terraform local_exec.

**Comment by Spritekin** [comment]
@leg100 What do you think about this:

```
FROM leg100/otfd:0.0.50

# Install aws cli if required
ARG INSTALL_AWSCLI=false
RUN INSTALL_AWSCLI & \
    apk add --no-cache aws-cli

# Install kubectl if required
ARG INSTALL_KUBECTL=false
RUN INSTALL_AWS & \
    curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/bin/kubectl

```

So people can use this dockerfile to build the image they need. For example:
docker build -t otfd --build-arg INSTALL_AWSCLI=true --build-arg INSTALL_KUBECTL=true .

Do you think it valuable to keep in the otfd repo? Maybe in a customdockerfile folder?

**Comment by leg100** [comment]
If it works for you, it looks good.

> Do you think it valuable to keep in the otfd repo? Maybe in a customdockerfile folder?

I think Docker is straight-forward and versatile enough that we can leave the in-repo dockerfile as basic as possible for users to then deploy or build upon to their heart's content.
