### ISSUE TITLE
Unexpected behaviour when POST'ing to the organizations endpoint without an accept header

### ISSUE THREAD

**Issue by ghost** [leg100/otf#5]
`POST` requests to the `/api/v2/organizations` endpoint without an `Accept` header produce a HTTP status 404:

```
$ curl -i https://localhost:8080/api/v2/organizations -d'{
  "data": {
    "type": "organizations",
    "attributes": {
      "name": "mycorp",
      "email": "sysadmin@mycorp.co"
    }
  }
}'
HTTP/2 404 
content-type: text/plain; charset=utf-8
x-content-type-options: nosniff
content-length: 19
date: Sat, 19 Jun 2021 17:30:34 GMT

404 page not found
```

My interpretation of [the JSON:API spec](https://jsonapi.org/format/#content-negotiation-servers) is that in this case the server should respond with `406 not acceptable`. I'm happy to make the change if that sounds correct?

**Comment by leg100** [comment]
I've deferred to the Terraform Cloud API docs for many decisions, including which status codes to return.

In this particular case, see the [Create Organization](https://www.terraform.io/docs/cloud/api/organizations.html#create-an-organization) documentation.

If you can demonstrate that TFC/TFE returns a 406 in the case you've described then please go ahead! It may be that the docs are not exhaustive.

**Comment by fergalk** [comment]
Just had a go in TFC and got a slightly unexpected result:

`{"errors":[{"status":"415","title":"invalid content type","detail":"content-type must be application/vnd.api+json"}]}`

With a `content-type` header and no `accept` header the request succeeded.
This actually lines up with the json api specs, although it's a shame it isn't documented in the terraform docs! I'll work on a PR to update this.
