### ISSUE TITLE
Handle VCS trigger patterns and trigger prefixes

### ISSUE THREAD

**Issue by Spritekin** [leg100/otf#521]
Right now when a repository is connected to a VCS repo, it triggers a run on any file change.

TFC provides the ability to define trigger patterns or prefixes allowing to trigger changes only when certain files or files in certain paths change allowing for a more fine grained control (i.e. no need to run if we have updates a .gitignore or github actions.

**Comment by leg100** [comment]
Yes, should be reasonably straight-forward to implement.
