### ISSUE TITLE
A run in a workspace should block other runs from starting in the same workspace

### ISSUE THREAD

**Issue by Spritekin** [leg100/otf#524]
I have a workspace with a VCS source. When I commit a file into the repository a run starts, all good.

But then, if after commiting I request a run to start in the same workspce, then the run immediately starts even when the run started due to the commit is already running.

This leads to a racing condition, for example:
a. A "merge-initiated" run is started due to a git merge and is in a planning state.
b. While this is happening, I start a run.
c. The manually initiated run starts and enters run state.
d. As both are planning, both runs detect changes and will try to create or destroy resources following the plan.
e. When they apply, resources created by one are detected by the other and causes an error.

Note this is related to issue 521 as the merge-run starts because I changed files that might or might not be relevant to the run, I don't want to start during the merge, I want to start the run manually.
https://github.com/leg100/otf/issues/521

**Comment by leg100** [comment]
Is either run a "plan-only" run? They are allowed to run in parallel. However, if not, then they should be queued, and the first run should block the second run.

> e. When they apply, resources created by one are detected by the other and causes an error.

What's the error?

**Comment by Spritekin** [comment]
No, I was doing tests runs and checking every step, OTF is working as expected and blocking runs appropriately. However as both runs were scheduled with seconds of difference it looked like they were running at the same time.

But I checked the run every second... here are some images. The name has the seconds of difference.
<img width="901" alt="Screenshot 2023-07-23 at 9 37 52 pm" src="https://github.com/leg100/otf/assets/13467740/5291802b-0b96-47a0-99a2-36dc75d067b1">


<img width="897" alt="Screenshot 2023-07-23 at 9 39 24 pm" src="https://github.com/leg100/otf/assets/13467740/77c96f7e-8428-4eee-aeb9-4eef09a2b293">
<img width="903" alt="Screenshot 2023-07-23 at 9 38 20 pm" src="https://github.com/leg100/otf/assets/13467740/efbb1a11-d95b-4ce8-a691-1fb9e2c41f52">
