### ISSUE TITLE
OIDC federation AKA dynamic credentials

### ISSUE THREAD

**Issue by leg100** [leg100/otf#529]
As per the [TFC docs](https://developer.hashicorp.com/terraform/cloud-docs/workspaces/dynamic-provider-credentials):

> Using static credentials in your workspaces to authenticate providers presents a security risk, even if you rotate your credentials regularly. Dynamic provider credentials improve your security posture by letting you provision new, temporary credentials for each run.

> You can configure dynamic credentials for each Terraform Cloud workspace. This workflow eliminates the need to manually manage and rotate credentials across your organization. It also lets you use the cloud platform’s authentication and authorization tools to scope permissions based on metadata, such as a run’s phase, its workspace, or its organization.

This is the "OIDC" people sometimes refer to, often w.r.t Github actions authenticating with a cloud provider, and it differs from the OIDC flow that one uses to interactively login to a service using an identity provider. I *think* what Github and TFC have implemented under the hood is referred to specifically as [OIDC _federation_](https://openid.net/specs/openid-connect-federation-1_0.html).

If OTF were to support this, an OTF adminstrator would have to:

* Publicly expose two endpoints, one for metadata document, one for the JWKs.
* Configure an SSL certificate signed by a public CA.

(You can see why you rarely see this implemented in self-hosted software).

And then for each workspace, they would add environment variables specifying various cloud provider OIDC configuration.

OTF would provide support for the three major cloud providers (AWS,GCP,Azure). For each run, it would check for presence of aforementioned environment variables and then retrieve temporary credentials accordingly, for the respective terraform providers to authenticate to the cloud provider.

Of course this is not the only way to get dynamic credentials. If OTF is deployed on the same cloud provider as it is managing infrastructure for, then you can attach a service account to the underlying compute resource and OTF inherits the permissions of the service account. For example, you could deploy OTF agents to different VMs or kubernetes pods, and then runs would inherit their permissions, e.g. on GCP with [GKE workload identity](https://cloud.google.com/iam/docs/workload-identities#kubernetes-workload-identity). This is a simpler approach and requires no configuration in OTF.

However, what OIDC federation gives you is the ability to use dynamic credentials across different cloud providers, e.g. if you deploy OTF on AWS, and then use OTF to provision GCP infrastructure, or vice-versa.

And it allows you to authenticate individual terraform runs. A run would authenticate with a temporary credential containing claims specifying properties of that run, including organization, workspace, user, etc, and the cloud provider can permit or deny access accordingly. Which is very powerful.

It would useful to know if anyone out there wants this functionality. And whether they're prepared to set it up, particularly publicly exposing the endpoints above.

**Comment by Spritekin** [comment]
I can see the importance, but IMO I think this might be overkill at this moment. There are other areas in OTF that can benefit from more attention like overall UI look and feel, better data presentation, more Workspace options, getting the logs without having to go to the CLI.

I think cleanup and presentation will have a huge impact on adoption.

**Comment by leg100** [comment]
> getting the logs without having to go to the CLI.

What do you mean? You can get the streaming logs on the UI.

**Comment by jlgore** [comment]
Hello, thank you for the project and all the hard work you have put into it. OIDC is great and would provide a lot of value to the project. I am not the best programmer but I would love to help and learn more.

**Comment by leg100** [comment]
@jlgore By all means take a stab at it. I don't want to put you off but I reckon it's going to be quite challenging. But yes, I agree, I think it would add a lot of value, providing fine-grained authorization with short-lived credentials.

**Comment by jlgore** [comment]
haha i appreciate the vote of confidence but probably too big for me to swing at today. I am looking at some of the good first issue tags and getting familiar with the codebase. If you have a Slack or Discord for community I would join as well.

**Comment by leg100** [comment]
> If you have a Slack or Discord for community I would join as well.

Please do, there's a Slack badge on the readme: https://github.com/leg100/otf

**Comment by leg100** [comment]
Archiving repo.

**Comment by kdpuvvadi** [comment]
is this in the pipeline?

**Comment by leg100** [comment]
> is this in the pipeline?

@kdpuvvadi No, not anytime soon anyway.
