### ISSUE TITLE
Deleting VCS shouldn't be possible if it is referenced by at least one workspace

### ISSUE THREAD

**Issue by fsaintjacques** [leg100/otf#546]
This was uncovered due to a side effect in the tfe provider.

1. The `tfe_oauth_client` is receiving the oauth_token via a data lookup.
2. Due to 1., the vcs provider is always replaced (delete then create).

We are expecting the deletion of a VCS provider to fail if it is referenced by at least one workspace instead of "unlinking".

**Comment by leg100** [comment]
Welcome back @fsaintjacques.

TFC behaves the same as OTF:

> Note: Removing the OAuth Client will unlink workspaces that use this connection from their repositories, and these workspaces will need to be manually linked to another repository.

https://developer.hashicorp.com/terraform/cloud-docs/api-docs/oauth-clients#destroy-an-oauth-client

I'm hesitant to deviate away from how TFC behaves.

Why does the `tfe` provider replace the OAuth client? Something to do with the data lookup?

**Comment by fsaintjacques** [comment]
I didn't know about this behavior. The issue is that the `oauth_token` [field](https://github.com/hashicorp/terraform-provider-tfe/blob/main/tfe/resource_tfe_oauth_client.go#L58) is set to ForceNew. The value is not known at plan time (when it comes from a data lookup) and thus triggers the ForceNew...

We managed to fix it by using a combination of [lifecycle.ignore_changes](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes), [lifecycle.replace_triggered_by](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#replace_triggered_by) and [terraform_data](https://developer.hashicorp.com/terraform/language/resources/terraform-data).
