### ISSUE TITLE
FR: Agent Pools

### ISSUE THREAD

**Issue by adamlc** [leg100/otf#570]
Thanks for the great work on otf!

It would be great if we could [pool agents like on terraform cloud](https://developer.hashicorp.com/terraform/tutorials/cloud/cloud-agents).

At the moment I can use different orgs to achieve the pooling, but it would be nice if there was a pool option too :)

Keep up the good work 😎

**Comment by leg100** [comment]
Which functionality is it you are specifically seeking from pools? The ability to assign agents to specific workspaces?

**Comment by adamlc** [comment]
Yes basically, or at the very least assign a single agent to a workspace
