### ISSUE TITLE
Generic git module source

### ISSUE THREAD

**Issue by georgegil** [leg100/otf#575]
Discovered this product and this is really good! Best non-commercial TFC/E product so far. 

Curious how much effort it would take to have a generic git+pat or git+ssh-key source for module?

For context, Attempting to present all Terraform modules through a single registry and currently we've got modules in GitHub and AzureDevops, and for long story reasons can't migrate to GitHub yet.

Being able to publish a module using a generic git url would be most useful.. 

Reckon full AzureDevops vcs integration is probably not a lot of demand for

**Comment by leg100** [comment]
Hello. To clarify, are we talking about adding ssh keys for cloning modules, like so:

https://developer.hashicorp.com/terraform/cloud-docs/workspaces/settings/ssh-keys

**Comment by georgegil** [comment]
That would be useful too.

But what I actually meant was being able to publish a module in the registry from a generic git provider as opposed to the existing GitHub and GitLab VCS services.

**Comment by leg100** [comment]
What's the motivation for a generic git provider? How would you keep the module up to date?

Publishing modules via VCS obviously has the advantage that they are automatically kept up to date. Each git tag push to the source repo triggers the webhook and OTF updates the module in its registry.

I notice TFC does not support publishing from a generic git provider either. It does support publishing modules via the API, which it presumably provides as a means for a user to script the update automation themselves.

I suppose I'm struggling to see the use-case and whether it would be useful for other folks.

**Comment by georgegil** [comment]
TFC does not do generic fit provider you are correct.

I have noticed this feature in Terrakube, which kidna gave me the idea.

Thing is, this is kinda of a compromise ask for other VCS products, like AzureDevops, BitBucket etc.. 

My main ask really is AzureDevops tbh, but thought this might be a reasonable compromise.

If not feasible then it's not a big deal. Most of my work is in GitHub...

**Comment by leg100** [comment]
I do intend to include support for other VCS's. I think that's a better idea than implementing a generic git provider. Or failing that, implement the API endpoints like TFC does.
