### ISSUE TITLE
Rerunning a failed run should update the CI status check

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#578]
I noticed when a run fails (for whatever reason) and one reruns the same run, the respective status check in the VCS provider stays at "failed". 

It would be nice if the status gets somehow linked to the most recent run. This would probably require to somehow link such runs, e.g. through a shared run ID or similar.

Currently only updating the branch/re-triggering the commit helps to trigger a status refresh. In these cases the update is related to a new commit ID and is therefore probably linking to a "new" OTF run.

**Comment by leg100** [comment]
Can you have a look as to how TFC handles this?

**Comment by pat-s** [comment]
We currently don't have any workspaces anymore in TFC. 

But in general I would think that when rerunning a OTF run, it should keep it's old run ID. 
I would be ok with deleting the previous run log/information entirely as keeping the old one and implementing a versioning there might be complicated.

Currently the "retry run" creates an entirely new run which is then unlinked to the status check related to the actual commit (or any commit in that case).

Do you think the above would be (somewhat easily) possible? I.e. that the "retry run" button 

1. infers it's current run ID
2. Starts a run with the respective run ID

If there are conflicts in the DB somehow it could delete it's previous entry. I don't really need the output of previous runs if they actually share the same config.

A practical scenario in which this happens: whenever I have the execution mode set to "local" for some reason and haven't changed it back before pushing a commit, the run won't be executed of course and when cancelling it and changing the exec mode to "Remote" or "Agent", the status check is not resolving. This is then blocking merges and I first need to trigger a new commit for a "clean" run.

**Comment by leg100** [comment]
Archiving repo.
