### ISSUE TITLE
Conflicting plugin cache access during concurrent runs

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#583]
With plugin cache enabled and multiple runs trying to access the same file, I get the following error

```
│ Error: Failed to install provider
│
│ Error while installing hashicorp/tls v4.0.4: open
│ /tmp/plugin-cache/registry.terraform.io/hashicorp/tls/4.0.4/linux_arm64/terraform-provider-tls_v4.0.4_x5:
│ text file busy
```

OTF is running on a VM with a RWO module. Maybe that's the culprit and using a RWX would be required in such cases?

For now I've disabled the plugin cache but I had it enabled since a long time and didn't have these issues in the past 🤔

**Comment by leg100** [comment]
I was waiting for this to become an issue. The plugin cache is not concurrency-safe:

> Note: The plugin cache directory is not guaranteed to be concurrency safe. The provider installer's behavior in environments with multiple terraform init calls is undefined.

https://developer.hashicorp.com/terraform/cli/config/config-file#provider-plugin-cache

Hence my recent proposal to hardcode concurrency to 1:

https://github.com/leg100/otf/issues/538#issue-1820875339

However, that would be a breaking change and I'm hesitant to make it. I would suggest in the meantime setting concurrency to 1 manually using `--concurrency 1`.

I'll add something to the docs regarding the cache. I may even implement some behaviour like so: if the plugin cache is enabled then concurrency is set automatically to 1.

**Comment by leg100** [comment]
Archiving repo.
