### ISSUE TITLE
Local apply not allowed despite option being enabled in OTF

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#584]
When invoking locally I get

```
╷
│ Error: Apply not allowed for workspaces with a VCS connection
│ 
│ A workspace that is connected to a VCS requires the VCS-driven workflow to ensure that the VCS remains the single source of truth.
```

despite having "Allow apply from the CLI" checked for this workspace

![image](https://github.com/leg100/otf/assets/8430564/7c170604-8ecb-4495-958b-6a7153c5cf55)

v0.1.8

**Comment by leg100** [comment]
What's your local version of terraform?

**Comment by pat-s** [comment]
1.5.5 or later (if there is)

**Comment by leg100** [comment]
It's working fine for me with 1.5.5. Can you confirm you're using the correct workspace.

**Comment by pat-s** [comment]
Jup. Double-checked now and also aligned local TF version with the remote one (both on 1.5.6 now).

**Comment by leg100** [comment]
Okay, I think I know the cause: are you using the "remote" backend, as opposed to the "cloud" block?

This functionality only works with the latter, because only the latter sends the necessary information (it's essentially a hack).

**Comment by leg100** [comment]
If that is indeed the case, I will:

* Place a note next to that checkbox.
* Update documentation to 'recommend' the cloud block, and move all example configurations in the documentation to use the cloud block. I think there are other things that work only with the cloud block, workspace tags for example.

**Comment by pat-s** [comment]
That's it!

I migrated to the "cloud" backend and now things are working as expected. Also toggled on/off the "allow local applies". 

A note like you suggested sounds great! Thanks for your help again :)
