### ISSUE TITLE
Feature: Multiple agents and pre-run hook

### ISSUE THREAD

**Issue by KamranBiglari** [leg100/otf#585]
Hello,
I want to have multiple agent and an ability to choose the agents. Also since I don't want to have a always on machine I need a hook or pre-run script to start a machine and register it.

**Comment by leg100** [comment]
When you say you want to ability to choose the agents, do you mean you want to tie workspaces to specific agents? e.g. agent A only executes runs for workspace A, agent B only executes runs for workspace B and C, etc.? There is an issue open already for that:

https://github.com/leg100/otf/issues/570#issuecomment-1680641984

As for pre-run hooks and starting machines...I have no plans to implement support for arbitrary hooks, e.g. execute a bash script before a run, etc. But what I am planning to do is support a "pluggable runtime". The default would remain, i.e spawn run on the local machine. But then there would be further options to either spawn a docker container for a run, or to spawn a kubernetes pod for a run. If you're running kubernetes, and you start 100 runs, then 100 pods would be spawned. Your cluster would auto-scale accordingly, provisioning machines as necessary.

Would that suffice?
