### ISSUE TITLE
Stance on OpenTF?

### ISSUE THREAD

**Issue by adamlc** [leg100/otf#607]
More of a general question really. What are your thoughts on OpenTF going forward? Are there any plans for support?

In theory, at least to begin with it should be a drop in replacement once its released, but may well diverge in the future. If possible having the option between both would be great!

**Comment by leg100** [comment]
OTF will support both OpenTF and terraform. They may well diverge over time and it'll be more work to support both. But we'll tackle that bridge when we come to it.

Open source projects are well positioned for this split. OTF has received dispensation from Hashicorp to continue embedding terraform, whereas I would suspect commercial competitors have not. Of course that dispensation can be retracted at any time. Nonetheless it's a preferable position to be in.

**Comment by adamlc** [comment]
Great to hear, once again thanks for all your hard work :)
