### ISSUE TITLE
Terraform version handling | dynamic updates

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#608]
We have a lot of workspaces meanwhile and changing the TF version in each of them becomes quite a task.

Removing the version from a workspaces, once set, is not supported at the moment. There is also no way to automatically use the latest TF version available AFAICS.

Proposal: allow to remove the hardcoded TF version field in a workspace and default to the latest available one?
Or alternatively allow to set an org-wide TF version for all workspaces.

**Comment by pat-s** [comment]
TFC provides a version option "latest" besides specific release versions

![image](https://github.com/leg100/otf/assets/8430564/ee72aa2e-68ea-430d-b7ad-74fcdb817de0)

**Comment by nokernel** [comment]
Does this means that a new version of terraform would be picked up at every apply|plan|... of this workspace?

**Comment by leg100** [comment]
The mechanics of how it works is slightly more complicated: a background
process checks for a new version every 24 hours and records it in the
database. That is the version a plan or apply uses.

**Comment by nokernel** [comment]
It is is concerning to me, as this can select a version with a bug and cause issues in the workspace. Multiple times Terraform core had bugs in it and caused issues.

I understand that someone could want to use this feature, but an option to turn this off at org level and globally would be nice ( if not the case ).

Im discussing here, I am not complaining here just sharing experience I had with Terraform.

**Comment by leg100** [comment]
It's not the default behavior.

**Comment by nokernel** [comment]
👍 good then
