### ISSUE TITLE
CLI applies sent to OTF agents error

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#612]
When doing the above, I get the following in the logs

```
2023/09/28 14:16:06 ERROR creating execution environment run=run-jJBxzkzje5asCisE phase=plan error="Internal Server Error: the `jsonapi:\"primary\"` field value must not be empty
```

and the following in the UI

![image](https://github.com/leg100/otf/assets/8430564/a0a2e32d-7c48-483b-8dd4-2560751c22ad)

otf 0.1.13

**Comment by leg100** [comment]
I cannot replicate the error.

When posting issues, please try the very simplest example. A new workspace, a single resource, etc.

**Comment by pat-s** [comment]
I've tried with a simple example workspace but I see the same fluctuating behavior there: it happens randomly on some runs and seems to differ randomly across workspaces.

As of now, we're still seeing this almost daily across various workspaces which are running on an agent. With > 10 workspaces, this becomes a bit unpractical at times.

I can't wrap my head around it, as in the end it should be the same webhook trigger sent by all of them - and I'd expect all repos to fail or none 🤔 
We also sometimes see it for workspaces running with "remote". 

I see it might be a local thing of ours given nobody else reported similar issues so far. Just letting you know - and sorry not being able to give more detailed insights to troubleshoot 🙏

(0.1.18)

**Comment by leg100** [comment]
Archiving repo.
