### ISSUE TITLE
Workspace run trigger

### ISSUE THREAD

**Issue by georgegil** [leg100/otf#614]
Question if OTF supports TFE-esque run triggers?

https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/run_trigger

I need to link two workspaced together, and have it run after the first finishes.

**Comment by leg100** [comment]
It doesn't. I'm aware of it however, and like many missing features I've been waiting for someone to need it before implementing it.

Not sure when though. Until then, we'll keep this issue open.

**Comment by georgegil** [comment]
Thanks for the response

If I was any good at `Go` I'd have contributed.. alas I am not.

**Comment by junkiebev** [comment]
I have a use case for this - I've a workspace which reference the output of another workspace and both have VCS triggers. The issue is that the "child" workspace fires off before the parent workspace's output has been updated (since it's still running)

**Comment by leg100** [comment]
> I have a use case for this - I've a workspace which reference the output of another workspace and both have VCS triggers. The issue is that the "child" workspace fires off before the parent workspace's output has been updated (since it's still running)

I don't think run triggers - as they exist in TFE - impose an order on the sequence in which a VCS event triggers runs for each workspace. Instead, a run for both workspace A (parent) and workspace B (child) would be triggered in parallel. If a run trigger exists then _another_ run would be enqueued for workspace B once workspace A finishes. Not sure if that would be satisfactory...

**Comment by leg100** [comment]
Archiving repo.

**Comment by that-devops-guy** [comment]
I have a use case for this, I have kubernetes core cluster installing in workspace A and then helm resources managed in a separate workspace B, Reason is i cannot initialise the Kubernetes or Helm provider in the same workspace, not until the kubernetes cluster is up. To tackle this we've separated the workspaces.

However I'd like the chaining capability of TFE run trigger here, it'll allow me to trigger workspace A and then B after sucessfull completion of A.
