### ISSUE TITLE
access denied to workspace variables

### ISSUE THREAD

**Issue by georgegil** [leg100/otf#633]
When a team has `admin` permissions on the workspace, they can't access the variables tab. 

Is this intentional or a possible bug?
 

![MicrosoftTeams-image](https://github.com/leg100/otf/assets/44511536/6089e190-727a-4891-af30-e1d1ba93dec8)

**Comment by leg100** [comment]
A very possible bug. Without looking at the code I suspect it's a regression when variable sets were added. Sets operate on the organization level so that's perhaps where workspace level permissions are insufficient.

I'll find a solution.

**Comment by leg100** [comment]
Fixed in https://github.com/leg100/otf/commit/df9fa53fad1e51c2c0b9e4d9ac4f493c5be66fb7

**Comment by georgegil** [comment]
Thanks!!! 

very quick indeed!
