### ISSUE TITLE
Expose workspace/runs metrics

### ISSUE THREAD

**Issue by fsaintjacques** [leg100/otf#641]
We would like to monitor OTF via metrics, but it is currently missing information on runs. The following metrics are what we would like to monitor:
- Highest number of pending runs per workspace (to detect workspaces with a backlog of runs)
- Longest non-finished run (to detect blocked runs)

**Comment by fsaintjacques** [comment]
Potentially add the workspace as a label.

**Comment by leg100** [comment]
Archiving repo.
