### ISSUE TITLE
Push event not triggering GitHub VCS trigger not working

### ISSUE THREAD

**Issue by kdpuvvadi** [leg100/otf#645]
Push event not triggering runs on the workspace even after multiple push events. but on docker log, i can that TLS handshake failures

```log
2023/10/31 09:19:13 INFO request duration=149263ms status=200 method=GET path="/app/workspaces/ws-CXhvuX7eEtdvz3Ec/watch?latest=true"
2023/10/31 09:19:18 http: TLS handshake error from 127.0.0.1:43725: tls: first record does not look like a TLS handshake
2023/10/31 09:19:28 http: TLS handshake error from 127.0.0.1:44509: tls: first record does not look like a TLS handshake
2023/10/31 09:19:38 http: TLS handshake error from 127.0.0.1:43787: tls: first record does not look like a TLS handshake
2023/10/31 09:19:48 http: TLS handshake error from 127.0.0.1:39191: tls: first record does not look like a TLS handshake
2023/10/31 09:19:58 http: TLS handshake error from 127.0.0.1:45539: tls: first record does not look like a TLS handshake
```

Does `otf ` needs to be publicly accessible? and running on docker behind `traefik`

**Comment by leg100** [comment]
Looks like traefik is trying to talk to otfd via plaintext http, whereas otfd is expecting https. Is that correct?

**Comment by kdpuvvadi** [comment]
> Looks like traefik is trying to talk to otfd via plaintext http, whereas otfd is expecting https. Is that correct?

Yes, pretty much.

**Comment by leg100** [comment]
I suggest you either:

a) configure traefik to instead forward traffic to otfd via https
b) disable SSL on otfd by omitting the `--ssl` flag

> are there any specific headers to be passed to the otfd?

No, none.

**Comment by kdpuvvadi** [comment]
Switched to https on traefik end but still the same. here's the traefik config for reference

```yaml
http:
  routers:
    otf:
      entryPoints:
        - "https"
      rule: "Host(`otf.local.puvvadi.net`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      service: otf
      tls: {}
  services:
    otf:
      loadBalancer:
        servers:
          - url: "https://10.20.20.110:8080"
        passHostHeader: true
  middlewares:
    https-redirectscheme:

    default-headers:

    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"
        - "100.64.0.0/10"

    secured:
      chain:
        middlewares:
        - default-headers

```

**Comment by kdpuvvadi** [comment]
tested with disabling ssl on `otfd` and disabling ssl on `traefik`. But vcs not triggering a run.

**Comment by kdpuvvadi** [comment]
bollocks 

In the prcess of trying, restarted the containers from portainer. postgres table seems to be lost. why not mount a volume to the postgres container `postgres_otf:/var/lib/postgresql/data` in the compose?

**Comment by robbert229** [comment]
> bollocks
> 
> In the prcess of trying, restarted the containers from portainer. postgres tables seems to be lost as the postgres data is not persistent. why not mount a volume to the postgres container `postgres_otf:/var/lib/postgresql/data` in the compose?
> 
> ```
> 2023/10/31 10:52:08 INFO OK   000001_create_tables.sql
> 2023/10/31 10:52:08 INFO OK   000002_insert_site_admin.sql
> 2023/10/31 10:52:08 INFO OK   000003_alter_table_workspace_lock.sql
> 2023/10/31 10:52:08 INFO OK   000004_add_workspace_latest_run_id.sql
> 2023/10/31 10:52:08 INFO OK   000005_create_agent_tokens_table.sql
> 2023/10/31 10:52:08 INFO OK   000006_add_logs_offset.sql
> 2023/10/31 10:52:08 INFO OK   000007_add_teams.sql
> .
> .
> .
> ```

Are you referring to the docker-compose in the root of the repository? As far as I know that is intended to be used for development, not an example of what to do in production.

**Comment by kdpuvvadi** [comment]
It's fine, i was testing only. In the production, i'm gonna use rds in the production, but issue is still there.

**Comment by leg100** [comment]
@kdpuvvadi I'll need much more info to diagnose further:

* the error message
* turning verbosity to maximum (`-v=9` and `--log-http-requests`) and posting full logs
* confirm the webhook is created on github.com
* configuration of webhook on github.com

**Comment by kdpuvvadi** [comment]
looks like problem was my otf instance was not publicly available and github was unable to reach the instance.
