### ISSUE TITLE
Webhook: allow triggering runs for non-default branches

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#647]
Currently, WH triggers only work for PRs and the default branch.

Pushes to other branches cause a 400 in the webhook

```
  "ref": "refs/heads/renovate/aws-5.x-lockfile",
```

![image](https://github.com/leg100/otf/assets/8430564/81d5dac6-4470-48bf-92a7-7ca94f39df68)

For reference, here are the repo settings

![image](https://github.com/leg100/otf/assets/8430564/6d43228a-b577-4a83-9456-9f125c08c82b)

**Comment by leg100** [comment]
There are two issues here:

* OTF mishandles branch names containing a forward slash (easily fixed)
* OTF follows the TFC behaviour and ignores changes to non-default branches

I'm hesitant to deviate from TFC unless a good case is made.

**Comment by leg100** [comment]
Archiving repo.
