### ISSUE TITLE
Webhooks: Ability to change hostname

### ISSUE THREAD

**Issue by arcdigital** [leg100/otf#668]
We are trying to deploy OTF to our internal k8s cluster (it's not accessible via the internet). Since OTF requires webhooks for the VCS integration, we have configured a separate ingress that only allows access to the /webhooks path from specific IPs. Currently OTF doesn't provide a way to configure the hostname used for webhooks (it just uses the same hostname as the rest of the app). If we could configure this hostname that would be really helpful.

**Comment by leg100** [comment]
Fixed by #670
