### ISSUE TITLE
Reverting from 0.2.0 to 0.1.x not possible

### ISSUE THREAD

**Issue by pat-s** [leg100/otf#677]
After the issues reported in #673 I've tried to revert to 0.1.18. Yet this doesn't seem to be possible as every workspace throws the following error after doing so:

```
scan FindWorkspacesBatch row: number of field descriptions must equal number of destinations, got 35 and 34
```

![image](https://github.com/leg100/otf/assets/8430564/933f905b-93cd-496d-a437-6753d68e3732)

Maybe 0.2.0 should actually be 1.0.0 as it contains breaking changes and downgrading is not possible?

**Comment by leg100** [comment]
Archiving repo.
