### ISSUE TITLE
Can't use repos with multiple slashes in the path

### ISSUE THREAD

**Issue by arcdigital** [leg100/otf#678]
The error is:
```
retrieving repository tarball: mkdirtemp gitlab-orgname-subgroup/subgroup2/the-repo-name-*: pattern contains path separator
```

I think it's because we have multiple subgroups (e.g. gitlab.com/orgname/subgroup1/subgroup2/repository) and it's not replacing the remaining part of the path with hyphens

**Comment by leg100** [comment]
Archiving repo.
